START RequestId: c5da8d63-57ef-4622-95af-0cde9136caf7 Version: $LATEST
{"Records": [{"eventVersion": "2.1", "eventSource": "aws:s3", "awsRegion": "us-east-2", "eventTime": "2019-09-03T19:37:27.192Z", "eventName": "ObjectCreated:Put", "userIdentity": {"principalId": "AWS:AIDAINPONIXQXHT3IKHL2"}, "requestParameters": {"sourceIPAddress": "205.255.255.255"}, "responseElements": {"x-amz-request-id": "D82B88E5F771F645", "x-amz-id-2": "vlR7PnpV2Ce81l0PRw6jlUpck7Jo5ZsQjryTjKlc5aLWGVHPZLj5NeC6qMa0emYBDXOo6QBU0Wo="}, "s3": {"s3SchemaVersion": "1.0", "configurationId": "828aa6fc-f7b5-4305-8584-487c791949c1", "bucket": {"name": "slstack-messagestore60e7afc8-fcvaaengplyv", "ownerIdentity": {"principalId": "A3I5XTEXAMAI3E"}, "arn": "arn:aws:s3:::lambda-artifacts-deafc19498e3f2df"}, "object": {"key": "963184458", "size": 1305107, "eTag": "b21b84d653bb07b05b1e6b33684dc11b", "sequencer": "0C0F6F405D6ED209E1"}}}]}
{"videoId": "963184458"}
[ERROR] NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.Traceback (most recent call last):  File "/var/task/handler.py", line 53, in handler    obj = s3.get_object(Bucket=bucket, Key=key)  File "/var/task/botocore/client.py", line 357, in _api_call    return self._make_api_call(operation_name, kwargs)  File "/var/task/botocore/client.py", line 676, in _make_api_call    raise error_class(parsed_response, operation_name)
END RequestId: c5da8d63-57ef-4622-95af-0cde9136caf7
REPORT RequestId: c5da8d63-57ef-4622-95af-0cde9136caf7	Init Duration: 0.09 ms	Duration: 15517.63 ms	Billed Duration: 15600 ms	Memory Size: 1280 MB	Max Memory Used: 1280 MB	
{"errorMessage": "An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.", "errorType": "NoSuchKey", "stackTrace": ["  File \"/var/task/handler.py\", line 53, in handler\n    obj = s3.get_object(Bucket=bucket, Key=key)\n", "  File \"/var/task/botocore/client.py\", line 357, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n", "  File \"/var/task/botocore/client.py\", line 676, in _make_api_call\n    raise error_class(parsed_response, operation_name)\n"]}